[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "chall"
languages = ["CXX"]
msvc-runtime = "static"

[target.nand_nor]
type = "interface"
compile-features = ["cxx_std_23"]
include-directories = ["vendor/nand_nor/"]

[target.chall]
type = "executable"
compile-features = ["cxx_std_23"]
compile-definitions = ["NOMINMAX"]
sources = ["src/**.cpp"]
include-directories = ["src/"]
link-libraries = ["nand_nor"]
unix.compile-options = [
    "-stdlib=libc++",
]
unix.link-options = ["-lc++", "-lc++abi", "-fuse-ld=lld"]
msvc.compile-options = ["/MP"]
clang.compile-options = ["-mno-sse"]
